DROP DATABASE IF EXISTS `JMJ`;
CREATE DATABASE JMJ;
USE JMJ;
DROP TABLE IF EXISTS `USERS`;
DROP TABLE IF EXISTS `RECORDS`;

CREATE TABLE USERS(
uid VARCHAR(20) not null,
pwd VARCHAR(20) not null,
PRIMARY KEY (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE records(
id INT(12) NOT NULL auto_increment,
temper FLOAT(8,4),
uid VARCHAR(20) NOT NULL,
dt DATETIME NOT NULL,
CONSTRAINT `FK_ID` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`),
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;